### ISSUE TITLE
Sync with page scrolling would be a big plus

### ISSUE THREAD

**Issue by jiewangjs** [asiloisad/pulsar-navigation-panel#1]
When page gets long, this feature seems to be an essential one. Hope it can be implemented.

**Comment by asiloisad** [comment]
I am not sure if you mean auto-scroll of tree with editor view or moving the cursor. Today, I have introduce auto-scroll with cursor and I hope you will like it :)

https://github.com/bacadra/atom-navigation-pane/releases/tag/v0.2.0 (available from Atom -> Settings -> Packages)

**Comment by jiewangjs** [comment]
I thought I mean what you understand. :) 
But am I missing something ? I updated this package today, and I cannot use it anymore, I mean it doesn't seem to appear even in the menu>package list. And I cannot revert the version back. 
Need Help !

**Comment by asiloisad** [comment]
I don't see any problems installing the package. Try delete .atom/packages/navigation-pane and install package agaian. I hope it resolve your the problem.

**Comment by jiewangjs** [comment]
![image](https://user-images.githubusercontent.com/11204422/136226062-bc8891a7-cb7d-45ad-bf28-3d6d17fc7134.png)
![image](https://user-images.githubusercontent.com/11204422/136226439-0636fb43-f48a-43d5-8c7e-ff05a7e9816a.png)
The problem still exists here. 
I have several computers, each one installed with atom and this package, each one is not able to show the supposed to be there navigation pane. 
The older version, ie. version 0.1 which I managed to get it work somehow. But when I upgrade according to your suggestion, the rightly installed package just show no trace in a normal workflow. 
Wierd problem !

**Comment by asiloisad** [comment]
the window that you displayed is from the package "atom-ide". in old versions "navigation-pane" used the service from the "atom-ide" package and items in the "Outline" window were created by the "navigation-pane". 
In newer versions i has deleted this service, because it blocked e.g. list of classes, methods and variables in python.

please use package pane by command "Navigation Pane: View Toggle".

e.g. python grammar:
![image](https://user-images.githubusercontent.com/29706474/136276767-dd7a77fa-6b23-449c-adf2-1cd5f7910870.png)

**Comment by jiewangjs** [comment]
Sorry for not being familiar with atom usage. 
Your method works fine. 
Thanks.

**Comment by asiloisad** [comment]
I am glad that all works fine and that the package is useful for you.
Best regards, SB
