### ISSUE TITLE
Panel toggle also toggles file tree view.  

### ISSUE THREAD

**Issue by aubreyz** [asiloisad/pulsar-navigation-panel#2]
This looks like it is going to be a great package that will cover many tree views in a very adaptable way. Happy to use it and help you debug (at least in Latex, Markdown). 

One issue for now is that if I use the Navigation pane: toggle 
then it toggles the file tree view on and off as well, which is a bit undesirable. Would probably be better to have the pane to the right and in its own split not shared with the file tree. 

If this is going to be useful beyond the heading tree viewers that already exist for Latex, Markdown and others you are going to need to allow easy user customization of the Regex (for example I might use non-standard redrafted names for LaTex headers, or want to show various other markups within the text in the structure. I might not want to show structured headers at all, and to use it as a flexible bookmarking system, or to show TODO flags.

**Comment by asiloisad** [comment]
hi @aubreyz,

I am proud that you are using this package :) 

in the package settings, you can select a default side for the navigation pane -- left or right. I was thinking about the problem of the hiding tree-view, but so far I have no idea how to solve it (except for changing the position of pane to the right). I will consider to change default side to the right.

in .tex files, the special markup can be used as `<text.1>%$%<text.2>`, `<text.1>%$$%<text.2>` etc. Few days ago i have changed that `\part{<text>}` is equal to level 4, so `\part{<text>}` is equal to `%$$$$% <text>` so it partially resolve your issue. i have introduce also a toc name to appear instead of section text, if exists e.g. `\section[title]{title is too long to show in toc}` show as `title toc`.

in the near future I will introduce an option to set a custom name for chapter commands and options for automatic name extraction based on parentheses of type `{<text>}`. that should satisfy your requests.

best regards

**Comment by asiloisad** [comment]
offtop @aubreyz
you can also look at my another package `bib-finder`. it does a good job of supplementing the search for citation items.
https://github.com/bacadra/atom-bib-finder

**Comment by asiloisad** [comment]
custom commands for latex are introduced in v0.2.18. please see this functionality and write if you like it :) 
best regards, sb

**Comment by aubreyz** [comment]
This sounds great. Am away from my computer for the next 2 weeks and will certainly get back to this then.
