### ISSUE TITLE
Real section level alternative ?

### ISSUE THREAD

**Issue by jiewangjs** [asiloisad/pulsar-navigation-panel#4]
Hi, I have read in the package readme: real section level.
What if this handling is not desired by some users, say we want the marker value designating the exact level, is there some easy hack to achieve this ?

Best Regards !

**Comment by asiloisad** [comment]
hi, i can introduce a setting to select which kind of level (user level or real level) to be used by markers :smile: and local toggle button at context menu of navigation-panel. is this what it was about?

**Comment by jiewangjs** [comment]
Hi, I think it is. 


On 5/8/2022 00:47，Sebastian ***@***.***> wrote：

hi, i can introduce a setting to select which kind of level (user level or real level) to be used by markers 😄 and local toggle button at context menu of navigation-panel. is this what it was about?

**Comment by asiloisad** [comment]
the future has been added. the problem is i cannot publish updates from few days, it look like some bug of apm. i have already ask about it, but there is no respond :/ https://github.com/atom/apm/issues/949 https://github.com/atom/atom.io/issues/232

however, you can install the latest package directly from github by shell command `apm install bacadra/atom-navigation-panel`.

**Comment by jiewangjs** [comment]
![image](https://user-images.githubusercontent.com/11204422/167277651-7bda4bcf-2a19-4755-b980-0788ca9e437a.png)
![image](https://user-images.githubusercontent.com/11204422/167277658-70062bb0-4913-475d-8000-b2198e9aca24.png)
![image](https://user-images.githubusercontent.com/11204422/167277666-5cc3be73-4604-438b-ad1d-7c9803e1a184.png)
Not working, am I doing something wrong ?
